### ISSUE TITLE
Newline in tablename

### ISSUE THREAD

**Issue by jhermann-github** [opentelekomcloud-docs/elastic-cloud-server#10]
**Newline in tablename should be removed (enhancement)**

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/faqs/login_and_connection/what_browser_version_is_required_to_remotely_log_in_to_an_ecs.rst
![! BUG - 2022-03-23 14_47_03 why new line is used 2](https://user-images.githubusercontent.com/102295233/159950401-8b22e839-0a4d-4739-9f41-28436981edd3.png)

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/faqs/login_and_connection/how_can_i_change_a_remote_login_port.rst
![! BUG - 2022-03-23 14_47_03 why new line is used](https://user-images.githubusercontent.com/102295233/159950809-4dfb156c-c542-4a9a-b015-cd17a94b1b94.png)

**Comment by vladimirhasko** [comment]
table names are fixed now. Issue in figure names is still persisting

**Comment by vladimirhasko** [comment]
We consider changing the figcaption parameter:
display: table-caption; to display: table-header-group;
which should fix the line break

**Comment by vladimirhasko** [comment]
table break lines are fixed

**Comment by jhermann-github** [comment]
The table names are fixed now, and the issue in figure names is still persisting. But from my point of view it's fine, therefore I'll close the issue.
