### ISSUE TITLE
Text are bold

### ISSUE THREAD

**Issue by jhermann-github** [opentelekomcloud-docs/elastic-cloud-server#11]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/faqs/creation_and_deletion/index.rst

Why is "**Delete**" are bold
![! BUG - 2022-03-23 14_37_34-delete are bold](https://user-images.githubusercontent.com/102295233/159951340-0cacbaad-9df6-46dd-8e8f-1e6b3c14fd81.png)

**Comment by vladimirhasko** [comment]
the source documentation has the Chapter with bold name and sphinx is taking the link name from chapter name where the bold is already present.
There are two options: Either keep it as it is as this is not real bug and if needed to fix it then address via original doc to remove chapter in bold. Or we can setup special rule that on indexed bold will be completely ignored.

**Comment by vladimirhasko** [comment]
this has been fixed some time ago therefore closing.
