### ISSUE TITLE
GPU-accelerated ECSs - please remove Computing-accelerated P3v because we do not have that in offering

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/elastic-cloud-server#118]
Issue on page:        https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/service_overview/ecs_specifications_and_types/gpu-accelerated_ecss.rst

please remove Computing-accelerated P3v because we do not have that in offering

Please check your selfes in OTC service description https://open-telekom-cloud.com/service-description

**Comment by robert1x2** [comment]
Any updates?

**Comment by vladimirhasko** [comment]
this is already address in our internal issue tracker
waiting for updated document to be reviewed

**Comment by vladimirhasko** [comment]
documentation finally fixed

**Comment by robert1x2** [comment]
thank you!
