### ISSUE TITLE
Enhancements for terminal window

### ISSUE THREAD

**Issue by jhermann-github** [opentelekomcloud-docs/elastic-cloud-server#12]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/faqs/file_upload_data_transfer/how_can_i_use_sftp_to_transfer_files_between_a_local_linux_computer_and_a_linux_ecs.rst
**Code comments seems to be default italic**
![! BUG - 2022-03-23 15_36_02 code comments seems to be default italic](https://user-images.githubusercontent.com/102295233/159952198-2da67129-17ff-4c89-9a9c-9b2be3779291.png)

Auto coloring works only sometimes good 
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/faqs/disk_management/how_can_i_adjust_system_disk_partitions.rst
![! BUG - 2022-03-23 15_58_15 code coloring](https://user-images.githubusercontent.com/102295233/159952772-ed2d157b-1dcb-461f-b383-0822a430c372.png)

**Comment by vladimirhasko** [comment]
[test.txt](https://github.com/opentelekomcloud-docs/elastic-cloud-server/files/8552935/test.txt)

**Comment by vladimirhasko** [comment]
1. this is default visualization of comments in any code editors. So from our POV not a problem but improvement/feature
2. We might try out changing pre-class="screen" to format type console
