### ISSUE TITLE
Missing copy Function for terminal window

### ISSUE THREAD

**Issue by jhermann-github** [opentelekomcloud-docs/elastic-cloud-server#13]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/troubleshooting/how_do_i_configure_atop_and_kdump_on_linux_ecss_for_performance_analysis.rst

Missing copy Function for terminal window (enhancement)
![! ENH - 2022-03-23 14_15_00 Missing copy](https://user-images.githubusercontent.com/102295233/159953703-c5b51453-d766-4f1f-8803-9bcde7daac62.png)

**Comment by vladimirhasko** [comment]
This might be possible to add but needs further development and more effort. 
Can come later

**Comment by vladimirhasko** [comment]
moved to general docsportal issues:
https://github.com/opentelekomcloud-docs/docsportal/issues/89
