### ISSUE TITLE
Login Using an SSH Key

### ISSUE THREAD

**Issue by barbara-verso** [opentelekomcloud-docs/elastic-cloud-server#148]
Issue on page:        https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/instances/logging_in_to_a_linux_ecs/login_using_an_ssh_key.rst

The username is not root, but linux or ubuntu (or maybe other usernames) depending on the OS

**Comment by mpristro** [comment]
Thank you, we will check

**Comment by mpristro** [comment]
Thank you for your request, based on it OCS-8940 ticket is created. We will proceed with it. As soon as it fixed we will inform you.
