### ISSUE TITLE
Service Overview Name

### ISSUE THREAD

**Issue by andswalz** [opentelekomcloud-docs/elastic-cloud-server#154]
Issue on page:        https://docs.otc.t-systems.com/compute.html
Please change Name of the Service "Compute" to "Computing" in order to align the service name with website, servicedescription etc.. . Everywhere "Computing" is the name of service, except in docs.. therefore please change accordingly

**Comment by SebastianGode** [comment]
Already fixed with https://github.com/opentelekomcloud-docs/docsportal/pull/181
@andswalz

**Comment by andswalz** [comment]
it is still compute. No changes have been made yet. please fix it

**Comment by SebastianGode** [comment]
You are accessing an old page.
Please open https://docs.otc.t-systems.com/ and navigate from there.
@andswalz

**Comment by andswalz** [comment]
ah yeah. thx!
