### ISSUE TITLE
API Usage Guidelines: empty space under the header

### ISSUE THREAD

**Issue by omelniko** [opentelekomcloud-docs/elastic-cloud-server#36]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/api-ref/source/api_usage_guidelines.rst

![image](https://user-images.githubusercontent.com/102943925/163103603-68be8886-1dc7-451b-9dab-73a276f8233a.png)
Maybe it is not an issue, but empty space looks a bit strange

**Comment by vladimirhasko** [comment]
this needs further investigation. The problem is related to breadcrumbs navigation

**Comment by vladimirhasko** [comment]
the issue is fixed now
