### ISSUE TITLE
API document: tables is overlapped

### ISSUE THREAD

**Issue by omelniko** [opentelekomcloud-docs/elastic-cloud-server#37]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/api-ref/source/apis_recommended/lifecycle_management/creating_an_ecs.rst
![image](https://user-images.githubusercontent.com/102943925/163104021-415d86f7-a576-400f-824a-768dffb9f50a.png)
tables is overlapped by menu on the right side and horizontal scrollbar presented at the bottom of the table, it is not comfortable

**Comment by gtema** [comment]
It is your personal perception. We find horizontal scroll comfortable enough and it provides universal solution for too wide tables. Without scroll we need to start breaking words in cells (like current HC does) and this looks really ugly.

**Comment by omelniko** [comment]
not an issue
