### ISSUE TITLE
Dot style is different

### ISSUE THREAD

**Issue by JochenHermannUlm** [opentelekomcloud-docs/elastic-cloud-server#7]
Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/resources_and_tags/tag_management/adding_tags.rst

Dot style is different in the Note
![! BUG - 2022-03-23 13_46_12-Adding Tags — Note dot is differnt](https://user-images.githubusercontent.com/102295233/159903540-ec43ec95-1e86-4776-8939-e507936b6c17.png)

**Comment by vladimirhasko** [comment]
this is not an issue.
Dot style is automatically changing based on which level the text/paragraph/note is.
This visualization is controlled by CSS.
