### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by JochenHermannUlm** [opentelekomcloud-docs/elastic-cloud-server#8]
All marked Links are not working:

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/troubleshooting/how_do_i_configure_atop_and_kdump_on_linux_ecss_for_performance_analysis.rst
![! BUG - 2022-03-23 14_04_38-Links are not working](https://user-images.githubusercontent.com/102295233/159944012-ecbce43c-c08e-433b-90c3-67836cf0483d.png)

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/faqs/disk_management/how_do_i_obtain_my_disk_name_in_the_ecs_os_using_the_device_identifier_provided_on_the_console.rst
![! BUG - 2022-03-23 16_12_19 Links are not working](https://user-images.githubusercontent.com/102295233/159944659-bc018808-41d1-4196-a21a-9a9ad4a99804.png)

**Comment by vladimirhasko** [comment]
This has been fixed and is already implemented in latest published version
