### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by JochenHermannUlm** [opentelekomcloud-docs/elastic-cloud-server#9]
This Links are wrong:

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/nics/enabling_nic_multi-queue.rst
"ECS Specifications and Types" link to "Service Overview"
![! BUG - 2022-03-23 12_09_46-Enabling NIC Multi-Queue — Elastic Cloud Server UMN](https://user-images.githubusercontent.com/102295233/159947596-a56c34c2-7dcf-4e6a-ac63-a033b99bd001.png)

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/nics/enabling_nic_multi-queue.rst
"Creating an ECS" link to "Getting Started"
![! BUG - 2022-03-23 12_29_49-wrong link - getting started](https://user-images.githubusercontent.com/102295233/159948145-70e9acdc-7056-484a-b590-01b5285ff4c9.png)

Issue on page: https://github.com/opentelekomcloud-docs/elastic-cloud-server/blob/main/umn/source/change_history.rst
"Creating an ECS" link to "Getting Started"
![! BUG - 2022-03-23 16_59_19 wrong link 2](https://user-images.githubusercontent.com/102295233/159948502-62aab9ea-e5fb-4189-8f9e-cce580cff5e9.png)
![! BUG - 2022-03-23 16_59_19 wrong link](https://user-images.githubusercontent.com/102295233/159948647-86bb68ce-b848-4dc4-891c-c9b52388390e.png)

"Getting Started" link to "Open Telekom Cloud Service Documentation"
![! BUG - 2022-03-23 17_01_59 wrong link to main page!](https://user-images.githubusercontent.com/102295233/159948866-6fb235b6-eaa8-496b-9822-008293815e21.png)

"CBR" link to "Open Telekom Cloud Service Documentation"
![! BUG - 2022-03-23 17_05_26 links to main page!](https://user-images.githubusercontent.com/102295233/159949113-037517e8-9f76-4a8f-9c93-7cd71d5274aa.png)

"CTS" link to "Open Telekom Cloud Service Documentation"
![! BUG - 2022-03-23 17_06_29 links to the main page!](https://user-images.githubusercontent.com/102295233/159949313-ae70da96-09d9-4002-bdfe-b7da50582a2c.png)

"Glossary" link to "The page you are requesting is not available..."
![! BUG - 2022-03-23 17_08_12 page not exist!](https://user-images.githubusercontent.com/102295233/159949656-f3dcf5a0-d79d-496f-9929-4a7f829989fc.png)

**Comment by vladimirhasko** [comment]
the issue has been fixed and is already published in latest version
